const MENU_DEFAULTS = Object.freeze({
  DISCOUNT_PERCENT: 0,
  PREPARATION_TIME_MINUTES: 15,
  PAGE_SIZE: 20
});

const ACTIVE_ORDER_STATUSES = Object.freeze([
  'PLACED',
  'ACCEPTED',
  'PREPARING',
  'READY_FOR_PICKUP',
  'ASSIGNED',
  'PICKED_UP'
]);

module.exports = {
  MENU_DEFAULTS,
  ACTIVE_ORDER_STATUSES
};
