const ORDER_STATUSES = Object.freeze({
  PLACED: 'PLACED',
  ACCEPTED: 'ACCEPTED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  PICKED_UP: 'PICKED_UP',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
});

const COMMISSION_SETTLEMENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  SETTLED: 'SETTLED'
});

const ORDER_DEFAULTS = Object.freeze({
  CURRENCY: 'BDT',
  ORDER_LOCK_TTL_SECONDS: 120
});

module.exports = {
  ORDER_STATUSES,
  COMMISSION_SETTLEMENT_STATUSES,
  ORDER_DEFAULTS
};
