const ORDER_STATUSES = Object.freeze({
  PLACED: 'PLACED',
  ACCEPTED: 'ACCEPTED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
});

const COMMISSION_SETTLEMENT_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  SETTLED: 'SETTLED'
});

const ORDER_DEFAULTS = Object.freeze({
  CURRENCY: 'BDT',
  ORDER_LOCK_TTL_SECONDS: 120
});

const ORDER_TRANSITION_MAP = Object.freeze({
  [ORDER_STATUSES.PLACED]: Object.freeze([
    ORDER_STATUSES.ACCEPTED,
    ORDER_STATUSES.CANCELLED
  ]),
  [ORDER_STATUSES.ACCEPTED]: Object.freeze([
    ORDER_STATUSES.PREPARING,
    ORDER_STATUSES.CANCELLED
  ]),
  [ORDER_STATUSES.PREPARING]: Object.freeze([
    ORDER_STATUSES.READY_FOR_PICKUP,
    ORDER_STATUSES.CANCELLED
  ]),
  [ORDER_STATUSES.READY_FOR_PICKUP]: Object.freeze([
    ORDER_STATUSES.ASSIGNED,
    ORDER_STATUSES.CANCELLED
  ]),
  [ORDER_STATUSES.ASSIGNED]: Object.freeze([
    ORDER_STATUSES.PICKED_UP,
    ORDER_STATUSES.CANCELLED
  ]),
  [ORDER_STATUSES.PICKED_UP]: Object.freeze([
    ORDER_STATUSES.DELIVERED
  ]),
  [ORDER_STATUSES.DELIVERED]: Object.freeze([]),
  [ORDER_STATUSES.CANCELLED]: Object.freeze([])
});

module.exports = {
  ORDER_STATUSES,
  COMMISSION_SETTLEMENT_STATUSES,
  ORDER_DEFAULTS,
  ORDER_TRANSITION_MAP
};
