const NOTIFICATION_TYPES = Object.freeze({
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED'
});

const NOTIFICATION_CHANNEL_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED'
});

const NOTIFICATION_RECIPIENT_ROLES = Object.freeze({
  CUSTOMER: 'customer',
  DELIVERYMAN: 'deliveryman',
  RESTAURANT_OWNER: 'restaurant_owner'
});

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNEL_STATUSES,
  NOTIFICATION_RECIPIENT_ROLES
};
