const {
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNEL_STATUSES,
  NOTIFICATION_RECIPIENT_ROLES
} = require('./constants');

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNEL_STATUSES,
  NOTIFICATION_RECIPIENT_ROLES
};
