const DELIVERY_PROFILE_DEFAULTS = Object.freeze({
  SEARCH_RADIUS_METERS: 5000,
  MAX_SEARCH_RADIUS_METERS: 50000
});

const DELIVERY_ASSIGNMENT_DEFAULTS = Object.freeze({
  SEARCH_RADIUS_METERS: 5000,
  MAX_SEARCH_RADIUS_METERS: 50000,
  CANDIDATE_LIMIT: 25,
  MAX_CANDIDATE_LIMIT: 100,
  LOCK_TTL_SECONDS: 15,
  MAX_LOCK_TTL_SECONDS: 120,
  ASSIGNMENT_TIMEOUT_MS: 3000,
  MAX_ASSIGNMENT_TIMEOUT_MS: 15000,
  MAX_LAST_SEEN_AGE_SECONDS: 120
});

const DELIVERY_VEHICLE_TYPES = Object.freeze({
  BIKE: 'bike',
  CYCLE: 'cycle',
  CAR: 'car',
  WALK: 'walk',
  OTHER: 'other'
});

const ACTIVE_DELIVERY_ORDER_STATUSES = Object.freeze([
  'ASSIGNED',
  'PICKED_UP'
]);

module.exports = {
  DELIVERY_PROFILE_DEFAULTS,
  DELIVERY_ASSIGNMENT_DEFAULTS,
  DELIVERY_VEHICLE_TYPES,
  ACTIVE_DELIVERY_ORDER_STATUSES
};
