const {
  DELIVERY_PROFILE_DEFAULTS,
  DELIVERY_ASSIGNMENT_DEFAULTS,
  DELIVERY_VEHICLE_TYPES,
  ACTIVE_DELIVERY_ORDER_STATUSES
} = require('./constants');

module.exports = {
  DELIVERY_PROFILE_DEFAULTS,
  DELIVERY_ASSIGNMENT_DEFAULTS,
  DELIVERY_VEHICLE_TYPES,
  ACTIVE_DELIVERY_ORDER_STATUSES
};
